name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ github.sha }}


      - name: Decode and write kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > /home/runner/work/_temp/kubeconfig
        shell: bash

      - name: Set KUBECONFIG environment variable
        run: |
          export KUBECONFIG=/home/runner/work/_temp/kubeconfig

      - name: Create namespace and deploy
        run: |
          sed -i "s|_{_NAMESPACE_}_|${{ secrets.NAMESPACE }}|g" k8s/deployment.yaml
          sed -i "s|_{_IMAGE_}_|${{ secrets.DOCKERHUB_USERNAME }}/web-app:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl create namespace webapp
          kubectl apply -f k8s/deployment.yaml
          sleep 10
          kubectl get pod -n webapp
